export const WINDOW_RESIZE = 'WINDOW_RESIZE';

export const UPDATE_SELECTED_ITEM = 'UPDATE_SELECTED_ITEM';
export const UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY';
export const ADD_ITEM_TO_CART_START = 'ADD_ITEM_TO_CART_START';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAILURE = 'ADD_ITEM_TO_CART_FAILURE';
export const SHOW_MOBILE_POPUP = 'SHOW_MOBILE_POPUP';
export const HIDE_MOBILE_POPUP = 'HIDE_MOBILE_POPUP';
