export const WINDOW_RESIZE = 'WINDOW_RESIZE';

export const SAVE_SHIPPING_ADDRESS_START = 'SAVE_SHIPPING_ADDRESS_START';
export const SAVE_SHIPPING_ADDRESS_SUCCESS = 'SAVE_SHIPPING_ADDRESS_SUCCESS';
export const SAVE_SHIPPING_ADDRESS_FAILURE = 'SAVE_SHIPPING_ADDRESS_FAILURE';

export const REFRESH_SHIPPING_METHOD = 'REFRESH_SHIPPING_METHOD';
export const SELECT_SHIPPING_METHOD = 'SELECT_SHIPPING_METHOD';
export const SAVE_SHIPPING_METHOD_START = 'SAVE_SHIPPING_METHOD_START';
export const SAVE_SHIPPING_METHOD_SUCCESS = 'SAVE_SHIPPING_METHOD_SUCCESS';
export const SAVE_SHIPPING_METHOD_FAILURE = 'SAVE_SHIPPING_METHOD_FAILURE';
export const GET_DATA_FROM_ZIPCODE_START = 'GET_DATA_FROM_ZIPCODE_START';
export const GET_DATA_FROM_ZIPCODE_SUCCESS = 'GET_DATA_FROM_ZIPCODE_SUCCESS';
export const GET_DATA_FROM_ZIPCODE_FAILURE = 'GET_DATA_FROM_ZIPCODE_FAILURE';
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';

export const SAVE_COUPON_START = 'SAVE_COUPON_START';
export const SAVE_COUPON_SUCCESS = 'SAVE_COUPON_SUCCESS';
export const SAVE_COUPON_FAILURE = 'SAVE_COUPON_FAILURE';
export const SET_COUPON = 'SET_COUPON';

export const INIT_PAYMENT_METHODS = 'INIT_PAYMENT_METHODS';
export const SAVE_PAYMENT_METHODS_SUCCESS = 'SAVE_PAYMENT_METHODS_SUCCESS';
export const SAVE_PAYMENT_METHODS_FAILURE = 'SAVE_PAYMENT_METHODS_FAILURE';

export const REFRESH_TOTALS = 'REFRESH_TOTALS';
export const UPDATE_ITEMS = 'UPDATE_ITEMS';

export const SET_STEP = 'SET_STEP';
export const SET_MAX_STEP = 'SET_MAX_STEP';

export const SET_MARKETING_CONSENT = 'SET_MARKETING_CONSENT';
export const SUBMIT_START = 'SUBMIT_START';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAILURE = 'SUBMIT_FAILURE';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
