<?php


namespace App\Test\Fixture\Acos;
use Cake\Core\Configure;
use Cake\Datasource\ConnectionManager;
use Cake\TestSuite\Fixture\TestFixture;

class AcosArosFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'table' => 'aros_acos',
        'connection' => 'default'
    ];
    public function init()
    {
        Configure::load('app', 'default', false);
        $dbToRead = Configure::read('Datasources.default.database');
        $defaultConnection = ConnectionManager::get('default');
        $insertStatement = "SELECT * FROM {$dbToRead}.aros_acos";
        $queryResults = $defaultConnection->execute($insertStatement)->fetchAll();
        foreach ($queryResults as $key => $queryResult) {
            $dataToImport[] = [
                'id' => $queryResult[0],
                'aro_id' => $queryResult[1],
                'aco_id' => $queryResult[2],
                '_create' => $queryResult[3],
                '_read' => $queryResult[4],
                '_update' => $queryResult[5],
                '_delete' => $queryResult[6],
            ];
        }
        /*debug($dataToImport);die('DIEING');*/
        $this->records = $dataToImport;
        parent::init(); // TODO: Change the autogenerated stub
    }

}

