<?php


namespace App\Test\Fixture\Acos;
use Cake\Core\Configure;
use Cake\Datasource\ConnectionManager;
use Cake\TestSuite\Fixture\TestFixture;

class AcosFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'table' => 'acos',
        'connection' => 'default'
    ];

    public function init()
    {
        Configure::load('app', 'default', false);
        $dbToRead = Configure::read('Datasources.default.database');
        $defaultConnection = ConnectionManager::get('default');
        $insertStatement = "SELECT * FROM {$dbToRead}.acos";
        $queryResults = $defaultConnection->execute($insertStatement)->fetchAll();
        foreach ($queryResults as $key => $queryResult) {
            $dataToImport[] = [
                'id' => $queryResult[0],
                'parent_id' => $queryResult[1],
                'model' => $queryResult[2],
                'foreign_key' => $queryResult[3],
                'alias' => $queryResult[4],
                'lft' => $queryResult[5],
                'rght' => $queryResult[6],
            ];
        }
        /*debug($dataToImport);die('DIEING');*/
        $this->records = $dataToImport;
        parent::init(); // TODO: Change the autogenerated stub
    }

}

