<?php


namespace App\Test\Fixture\Acos;
use Cake\TestSuite\Fixture\TestFixture;

class ArosFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'table' => 'aros',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'model' => 'CoreUserRoles',
                'foreign_key' => '1',
                'lft' => '1',
                'rght' => '2',
            ],
            [
                'model' => 'CoreUsers',
                'foreign_key' => '1',
                'lft' => '3',
                'rght' => '4',
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}

