<?php

namespace EbayCheckout\Test\Fixture;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * EbayCheckoutSessionItemsFixture
 *
 */
class EbayCheckoutSessionItemsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'EbayCheckoutSessionItems',
        'connection' => 'default'
    ];
    // @codingStandardsIgnoreEnd
    /**
     * Records
     *
     * @var array
     */

    public function init()
    {
        $this->records = [
            [
            'id'                                              => 1,
            'ebay_checkout_session_id'                        => 1,
            'selected_ebay_checkout_session_item_shipping_id' => 1,
            'title'                                           => 'Frauen Baumwollmischung Socken Avocado / Kuchen / Sushi / Apfel / Toast / D E7Z9',
            'short_description'                               => 'New with tags, #9',
            'base_price_currency'                             => 'EUR',
            'base_price_value'                                => 1.83,
            'ebay_category_path'                              => "http://ebay.com/category",
            'image'                                           => 'https://i.ebayimg.com/00/s/MTAwMVgxMDAx/z/VUgAAOSwBSxbBmaH/$_3.JPG',
            'ebay_item_id'                                    => 'v1|372315975605|641139695655',
            'ebay_line_item_id'                               => 420002,
            'net_price_currency'                              => 'EUR',
            'net_price_value'                                 => 1.83,
            'quantity'                                        => 1,
            'seller_username'                                 => 'Lorem ipsum dolor sit amet',
            'seller_account_type'                             => 'Lorem ipsum dolor sit amet',
            'seller_feedback_score'                           => 'Lorem ipsum dolor sit amet',
            'seller_feedback_percentage'                      => 'Lorem ipsum dolor sit amet',
            'modified'                                        => '2017-10-25 17:03:25',
            'created'                                         => '2017-10-25 17:03:25'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
