<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderInvoiceRangesFixture
 *
 */
class CoreOrderInvoiceRangesFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'CoreOrderInvoiceRanges',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_seller_id' => 1,
                'core_marketplace_id' => 1,
                'name' => 'Lorem ipsum dolor sit amet',
                'invoice_incremental_value' => 1,
                'invoice_prefix' => 'Lorem ipsum dolor sit amet',
                'invoice_suffix' => 'Lorem ipsum dolor sit amet',
                'created' => '2016-04-06 11:16:00',
                'modified' => '2016-04-06 11:16:00'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
