<?php

namespace App\Test\Fixture\Core;

use Cake\I18n\FrozenTime;
use Cake\TestSuite\Fixture\TestFixture;

class CoreCategoriesCoreProductsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCategoriesCoreProducts',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'core_product_id' => 1,
                'core_category_id' => 1,
                'created' => new FrozenTime(\time()),
                'modified' => new FrozenTime(\time())
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
