<?php


namespace App\Test\Fixture\Core;


use Cake\I18n\FrozenTime;
use Cake\TestSuite\Fixture\TestFixture;

class CoreAccountTypesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'table' => 'core_account_types',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'code' =>    'administrator',
                'name' => "Administrator",
                'redirect_url' => 'itool-core/core-users',
                'created' => new FrozenTime(\time()),
                'modified' => new FrozenTime(\time()),
            ],
            [
                'code' =>    'ebay_seller',
                'name' => "eBay Seller",
                'redirect_url' => 'itool-core/core-orders',
                'created' => new FrozenTime(\time()),
                'modified' => new FrozenTime(\time()),
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
