<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreUsersFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreUsers',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => (int)1,
                'core_seller_id' => (int)1,
                'core_language_id' => (int)1,
                'is_active' => true,
                'is_deleted' => false,
                'first_name' => 'test',
                'last_name' => 'test',
                'email' => 'test@i-ways.net',
                'password' => '12345678',
                'company_name' => null,
                'street_line_1' => null,
                'street_line_2' => null,
                'city' => null,
                'postal_code' => null,
                'phone_number' => null,
                'redirect_url' => null,
                'reset_password_token' => 'xyz',
            ],
            [
                'id' => (int)2,
                'core_seller_id' => (int)2,
                'core_language_id' => (int)1,
                'is_active' => false,
                'is_deleted' => false,
                'first_name' => 'test',
                'last_name' => 'test',
                'email' => 'test2@i-ways.net',
                'password' => '12345678',
                'company_name' => null,
                'street_line_1' => null,
                'street_line_2' => null,
                'city' => null,
                'postal_code' => null,
                'phone_number' => null,
                'redirect_url' => null,
                'reset_password_token' => 'xyz',
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
