<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreCancelReasonsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCancelReasons',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_seller_id' => 1,
                'code' => 'Lorem ipsum dolor sit amet',
                'name' => 'Lorem ipsum dolor sit amet',
                'created' => '2016-02-03 15:01:23',
                'modified' => '2016-02-03 15:01:23'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
