<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderStatesFixture
 *
 */
class CoreOrderStatesFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model'      => 'CoreOrderStates',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'code' => 'Lorem ipsum dolor sit amet',
                'name' => 'Lorem ipsum dolor sit amet',
                'created' => '2015-04-23 14:00:50',
                'modified' => '2015-04-23 14:00:50'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
