<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreUserRolesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreUserRoles',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_seller_id' => 1,
                'code' => 'Dealsguru-ADMINISTRATOR',
                'name' => 'Dealsguru-Administrator',
                'created' => '2016-02-22 12:17:06',
                'modified' => '2016-02-22 12:17:06'
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
