<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderStatusHistoriesFixture
 *
 */
class CoreOrderStatusHistoriesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreOrderStatusHistories',
        'connection' => 'default'
    ];

    // @codingStandardsIgnoreEnd

    /**
     * Records
     *
     * @var array
     */
    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_order_id' => 1,
                'state_code' => 'Lorem ipsum dolor sit amet',
                'state_name' => 'Lorem ipsum dolor sit amet',
                'status_code' => 'fadd',
                'status_name' => 'Done',
                'comment' => 'testing',
                'email_notification_completed' => 0,
                'external_action_completed' => 0,
                'created' => '2015-04-23 14:03:13',
                'modified' => '2015-04-23 14:03:13'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
