<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreCurrenciesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCurrencies',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'code' => 'Lorem ipsum dolor sit amet',
                'symbol' => 'Lorem ipsum dolor sit amet',
                'name' => 'Lorem ipsum dolor sit amet',
                'created' => '2015-04-23 14:01:41',
                'modified' => '2015-04-23 14:01:41'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
