<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderProductsFixture
 *
 */
class CoreOrderChargesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'CoreOrderCharges',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_order_id' => 1,
                'code' => 'JHKJ12',
                'name' => 'Lorem ipsum dolor sit amet',
                'amount' => 13.22,
                'is_amount_incl_tax' => 1,
                'tax_percent' => 10,
                'sort_order' => 1,
                'created' => '2015-11-06 11:06:44',
                'modified' => '2015-11-06 11:06:44'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
