<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderProductsFixture
 *
 */
class CoreOrderProductsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'CoreOrderProducts',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
            'id' => 1,
            'core_order_id' => 1,
            'core_product_id' => 1,
            'sku' => 'Lorem ipsum dolor sit amet',
            'name' => 'Lorem ipsum dolor sit amet',
            'single_price' => 1,
            'is_price_incl_tax' => 1,
            'tax_percent' => 1,
            'quantity' => 1,
            'external_identifier' => 'Lorem ipsum dolor sit amet',
            'external_fee_amount' => '',
            'created' => '2015-11-06 11:06:44',
            'modified' => '2015-11-06 11:06:44'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
