<?php


namespace App\Test\Fixture\Core;


use Cake\I18n\FrozenTime;
use Cake\TestSuite\Fixture\TestFixture;

class CoreLanguagesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'table' => 'core_languages',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'iso_code' =>    'de',
                'name' => "Deutsch",
                'created' => new FrozenTime(\time()),
                'modified' => new FrozenTime(\time()),
            ],
            [
                'iso_code' =>    'en',
                'name' => "English",
                'created' => new FrozenTime(\time()),
                'modified' => new FrozenTime(\time()),
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
