<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreShippingMethodsFixture
 *
 */
class CoreProductSkuMappingsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'CoreProductSkuMappings',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_seller_id' => 1,
                'sku' => 'Lorem ipsum dolor sit amet',
                'mapping_sku' => 'Lorem ipsum dolor sit amet',
                'created' => '2016-02-03 14:56:04',
                'modified' => '2016-02-03 14:56:04'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
