<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreMarketplaceGroupsFixture
 *
 */
class CoreMarketplaceGroupsFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'CoreMarketplaceGroups',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'code' => 'Lorem ipsum dolor sit amet',
                'name' => 'Lorem ipsum dolor sit amet',
                'created' => '2016-02-10 15:01:13',
                'modified' => '2016-02-10 15:01:13'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
