<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreCountriesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCountries',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'iso_code' => 'DE',
                'iso_code_3166_2' => 'DE',
                'name' => 'Deutschland',
                'default_tax' => 19,
                'created' => '2016-01-22 13:19:21',
                'modified' => '2016-01-22 13:19:21'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
