<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreCustomerAddressesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCustomerAddresses',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_seller_id' => 1,
                'core_customer_id' => 1,
                'firstname' => 'Lorem ipsum dolor sit amet',
                'lastname' => 'Lorem ipsum dolor sit amet',
                'company' => 'Lorem ipsum dolor sit amet',
                'email' => 'Lorem ipsum dolor sit amet',
                'phone' => 'Lorem ipsum dolor sit amet',
                'street_1' => 'Lorem ipsum dolor sit amet',
                'street_2' => 'Lorem ipsum dolor sit amet',
                'postcode' => 'Lorem ipsum dolor sit amet',
                'city' => 'Lorem ipsum dolor sit amet',
                'country_code' => 'Lorem ipsum dolor sit amet',
                'country_name' => 'Lorem ipsum dolor sit amet',
                'created' => '2015-04-24 11:56:40',
                'modified' => '2015-04-24 11:56:40'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
