<?php


namespace App\Test\Fixture\Core;


use Cake\TestSuite\Fixture\TestFixture;

class CoreUserRolesCoreUsersFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreUserRolesCoreUsers',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'core_user_role_id' => 1,
                'core_user_id' => 1,
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
