<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreMarketplaceRunningProfilesFixture
 *
 */
class CoreMarketplaceRunningProfilesFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'CoreMarketplaceRunningProfiles',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_marketplace_id' => 1,
                'account_id' => 1,
                'running_type' => 'Lorem ipsum dolor sit amet',
                'is_running' => 1,
                'is_active' => 1,
                'last_start' => '2016-03-09 15:47:08',
                'next_start' => '2016-03-09 15:47:08',
                'run_interval' => 1,
                'last_alive' => '2016-03-09 15:47:08',
                'created' => '2016-03-09 15:47:08',
                'modified' => '2016-03-09 15:47:08'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
