<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderInvoicesFixture
 *
 */
class CoreOrderInvoicesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreOrderInvoices',
        'connection' => 'default'
    ];

    // @codingStandardsIgnoreEnd

    /**
     * Records
     *
     * @var array
     */
    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_order_id' => 1,
                'core_order_invoice_range_id' => 1,
                'invoice_number' => 1,
                'invoice_date' => '2015-04-23 14:03:13',
                'invoice_pdf' => 'Lorem ipsum dolor sit amet',
                'created' => '2015-04-23 14:03:13',
                'modified' => '2015-04-23 14:03:13'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
