<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreMarketplacesFixture
 *
 */
class CoreMarketplacesFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'CoreMarketplaces',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'core_marketplace_group_id' => 1,
                'code' => 'Lorem ipsum dolor sit amet',
                'name' => 'Lorem ipsum dolor sit amet',
                'is_default' => 1,
                'is_active' => 1,
                'created' => '2016-02-03 14:37:34',
                'modified' => '2016-02-03 14:37:34'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
