<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderShipmentsFixture
 *
 */
class CoreOrderShipmentsFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'CoreOrderShipments',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
            'id' => 1,
            'core_seller_id' => 1,
            'shipment_date' => '2015-11-18 10:16:36',
            'carrier_code' => 'WERSD3',
            'carrier_name' => 'Lorem ipsum dolor sit amet',
            'tracking_code' => 'QWE123',
            'tracking_link' => 'Lorem ipsum dolor sit amet',
            'shipping_label'=> 'lorem:testing;test,ipsum,dolor',
            'created' => '2015-11-18 10:16:36',
            'modified' => '2015-11-18 10:16:36'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
