<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class CoreCarriersFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'CoreCarriers',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'name' => 'Lorem ipsum dolor sit amet',
                'code' => 'WERSD3',
                'tracking_link' => 'Lorem ipsum dolor sit amet',
                'created' => '2016-02-03 14:48:02',
                'modified' => '2016-02-03 14:48:02'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
