<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * CoreOrderShipmentItemsFixture
 *
 */
class CoreOrderShipmentItemsFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'CoreOrderShipmentItems',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id'                     => 1,
                'core_order_shipment_id' => 1,
                'core_order_id'          => 1,
                'core_order_product_id'  => 1,
                'quantity'               => 1,
                'is_processed'           => 1,
                'created'                => '2015-11-06 11:06:44',
                'modified'               => '2015-11-06 11:06:44'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
