<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * EbayLaunchProfilesFixture
 *
 */
class EbayLaunchProfilesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'EbayLaunchProfiles',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id'                             => 1,
                'ebay_lister_type_id'            => 1,
                'ebay_account_id'                => 1,
                'ebay_site_id'                   => 1,
                'ebay_auction_type_id'           => 1,
                'core_seller_id'                 => 1,
                'core_language_id'               => 1,
                'name'                           => 'Lorem ipsum dolor sit amet',
                'duration'                       => 'Lorem ipsum dolor sit amet',
                'max_quantity'                => 1,
                'quantity_restriction_per_buyer' => 1,
                'use_subtitle'                   => 1,
                'use_eps_service'                => 1,
                'location_city'                => 'lahore',
                'ebay_shipping_profile_id'       => 1,
                'ebay_return_profile_id'       => 1,
                'ebay_payment_profile_id'       => 1,
                'ebay_shipping_profile_name'     => 'Lorem ipsum dolor sit amet',
                'ebay_return_profile_name'       => 'Lorem ipsum dolor sit amet',
                'ebay_payment_profile_name'      => 'Lorem ipsum dolor sit amet',
                'created'                        => '2015-08-06 12:07:55',
                'modified'                       => '2015-08-06 12:07:55'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
}
