<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * EbayAutoListerConfigurationsFixture
 *
 */
class EbayAutoListerConfigurationsFixture extends TestFixture
{

    public $connection = 'test';
    public $import = [
        'model' => 'EbayAutoListerConfigurations',
        'connection' => 'default'
    ];
 
    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'ebay_lister_type_id' => 1,
                'ebay_account_id' => 1,
                'ebay_site_id' => 1,
                'ebay_auction_type_id' => 1,
                'ebay_condition_id' => 1,
                'core_seller_id' => 1,
                'core_language_id' => 1,
                'core_currency_id'=>1,
                'name' => 'Lorem ipsum dolor sit amet',
                'duration' => 'Lorem ipsum dolor sit amet',
                'max_quantity' => 1,
                'quantity_restriction_per_buyer' => 1,
                'use_subtitle' => 1,
                'use_eps_service' => 1,
                'location_city'=> 'lahore',
                'is_active' => 1,
                'created' => '2015-08-07 13:39:22',
                'modified' => '2015-08-07 13:39:22'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
