<?php
namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

/**
 * EbayListingsFixture
 *
 */
class EbayDisputeExplanationNames extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'EbayListings',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'ebay_launch_profile_id' => 1,
                'ebay_lister_type_id' => 1,
                'ebay_account_id' => 1,
                'ebay_site_id' => 1,
                'ebay_auction_type_id' => 1,
                'ebay_condition_id' => 1,
                'core_seller_id' => 1,
                'core_language_id' => 1,
                'core_product_id' => 1,
                'sku' => 'Lorem ipsum dolor sit amet',
                'ean' => 'Lorem ipsum dolor sit amet',
                'ebay_item_id' => 'Lorem ipsum dolor sit amet',
                'title' => 'Lorem ipsum dolor sit amet',
                'subtitle' => 'Lorem ipsum dolor sit amet',
                'ebay_category_id' => 1,
                'start_price' => '',
                'current_price' => '',
                'currency' => 'Lorem ip',
                'quantity' => 1,
                'quantity_sold' => 1,
                'duration' => 'Lorem ipsum dolor sit amet',
                'max_quantity' => 1,
                'quantity_restriction_per_buyer' => 1,
                'use_subtitle' => 1,
                'use_eps_service' => 1,
                'location_city' => 'Lorem ipsum dolor sit amet',
                'location_postal_code' => 'Lorem ipsum dolor sit amet',
                'location_country' => 'Lorem ipsum dolor sit amet',
                'ebay_shipping_profile_id' => 'Lorem ipsum dolor ',
                'ebay_shipping_profile_name' => 'Lorem ipsum dolor sit amet',
                'ebay_return_profile_id' => 'Lorem ipsum dolor ',
                'ebay_return_profile_name' => 'Lorem ipsum dolor sit amet',
                'ebay_payment_profile_id' => 'Lorem ipsum dolor ',
                'ebay_payment_profile_name' => 'Lorem ipsum dolor sit amet',
                'start_time' => '2016-01-26 12:28:13',
                'end_time' => '2016-01-26 12:28:13',
                'listing_status' => 'Lorem ipsum dolor sit amet',
                'bid_count' => 1,
                'hit_counter' => 'Lorem ipsum dolor sit amet',
                'hit_count' => 1,
                'watch_count' => 1,
                'has_variations' => 1,
                'created' => '2016-01-26 12:28:13',
                'modified' => '2016-01-26 12:28:13'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }


}
