<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class EbaySitesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'EbaySites',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => 1,
                'name' => 'Lorem ipsum dolor sit amet',
                'ebay_site_code_type' => 'Lorem ipsum dolor sit amet',
                'language' => 'Lorem ip',
                'ebay_site_id' => 1,
                'ebay_global_id' => 'Lorem ipsum dolor ',
                'core_currency_id'=>1,
                'is_active' => 1,
                'created' => '2015-07-23 11:42:38',
                'modified' => '2015-07-23 11:42:38'
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
