<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class TranslationCoreCountriesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model' => 'TranslationCoreCountries',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id' => (int)1,
                'locale' => 'de',
                'model' => 'CoreCountries',
                'foreign_key' => 1,
                'field' => 'name',
                'content' => 'Deutsch',
            ]
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
