<?php

namespace App\Test\Fixture\Core;

use Cake\TestSuite\Fixture\TestFixture;

class TranslationCoreAttributesFixture extends TestFixture
{
    public $connection = 'test';
    public $import = [
        'model'      => 'TranslationCoreAttributes',
        'connection' => 'default'
    ];

    public function init()
    {
        $this->records = [
            [
                'id'          => 1,
                'locale'      => 'asdf',
                'model'       => 'Lorem ipsum dolor sit amet',
                'foreign_key' => 1,
                'field'       => 'Lorem ipsum dolor sit',
                'content'     => 'Lorem ipsum dolor sit'
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}
